import 'package:bitcoin_ticker/model/CryptoCurrency.dart';

const List<String> fiatCurrencyNames = [
  'AUD',
  'BGN',
  'BRL',
  'CAD',
  'CNY',
  'EUR',
  'GBP',
  'INR',
  'JPY',
  'NZD',
  'USD',
];

List<CryptoCurrency> cryptoCurrenciesList = [
  CryptoCurrency('AAVE', false),
  CryptoCurrency('ADA', false),
  CryptoCurrency('ATOM', false),
  CryptoCurrency('AVAX', false),
  CryptoCurrency('BTC', true),
  CryptoCurrency('CAKE', false),
  CryptoCurrency('CRV', false),
  CryptoCurrency('DOT', false),
  CryptoCurrency('EGLD', false),
  CryptoCurrency('ETH', true),
  CryptoCurrency('FIL', false),
  CryptoCurrency('KSM', false),
  CryptoCurrency('LINK', false),
  CryptoCurrency('LTC', true),
  CryptoCurrency('MATIC', false),
  CryptoCurrency('NEAR', false),
  CryptoCurrency('NEO', false),
  CryptoCurrency('REN', false),
  CryptoCurrency('SOL', false),
  CryptoCurrency('SNX', false),
  CryptoCurrency('SXP', false),
  CryptoCurrency('THETA', false),
  CryptoCurrency('UNI', false),
  CryptoCurrency('UTK', false),
  CryptoCurrency('VET', false),
  CryptoCurrency('XEM', false),
];
